backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "projects"
    label: "Проекты"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Название", widget: "string" }
      - { name: "slug", label: "Slug", widget: "string" }
      - { name: "description", label: "Описание", widget: "string" }
      - { name: "date", label: "Дата", widget: "datetime" }
      - { name: "cover", label: "Обложка", widget: "image" }
      - { name: "tech", label: "Технологии", widget: "list" }
      - { name: "body", label: "Текст", widget: "markdown" }

  - name: "blog"
    label: "Блог / Сертификаты"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Заголовок", widget: "string" }
      - { name: "slug", label: "Slug", widget: "string" }
      - { name: "date", label: "Дата", widget: "datetime" }
      - { name: "cover", label: "Обложка", widget: "image" }
      - { name: "body", label: "Текст", widget: "markdown" }

  - name: "pages"
    label: "Страницы"
    files:
      - file: "src/pages/about.tsx"
        label: "О себе"
        name: "about"
        fields:
          - { label: "Содержание", name: "body", widget: "markdown" }
      - file: "src/pages/skills.tsx"
        label: "Навыки"
        name: "skills"
        fields:
          - { label: "Содержание", name: "body", widget: "markdown" }
      - file: "src/pages/resume.tsx"
        label: "Резюме"
        name: "resume"
        fields:
          - { label: "Содержание", name: "body", widget: "markdown" }
      - file: "src/pages/contact.tsx"
        label: "Контакты"
        name: "contact"
        fields:
          - { label: "Содержание", name: "body", widget: "markdown" }